language: ruby
rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0
cache: bundler
branches:
  only:
    - master
script:
  - for file in $(ls examples/*.rb); do time bundle exec ruby $file; echo; done
  - for file in $(ls examples/yaml/*.yml); do time bundle exec exe/benchmark-driver $file; echo; done
