language: ruby
rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0
cache: bundler
branches:
  only:
    - master
install:
  - ruby -S gem install bundler --version 1.15.4
  - ruby -S bundle _1.15.4_ install -j4 --without docs
script:
  - ruby -S bundle _1.15.4_ exec rake ruby_examples
  - ruby -S bundle _1.15.4_ exec rake yaml_examples
