language: ruby
rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
cache: bundler
branches:
  only:
    - master
script:
  - bundle exec rake ruby_examples
  - bundle exec rake yaml_examples
