language: ruby
rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - ruby-head
cache: bundler
branches:
  only:
    - master
before_install: gem install bundler -v 1.15.4
script:
  - bundle exec exe/benchmark-driver
  - bundle exec rake run_examples
